Challenge.Presentation.Web/Controllers/HomeController.cs
using Challenge.ClientConnector.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace Challenge.Presentation.Web.Controllers
{
    public class HomeController : Controller
    {
        IChallengeServiceConnector ChallengeServiceConnector { get; }

        public HomeController(IChallengeServiceConnector challengeServiceConnector)
        {
            ChallengeServiceConnector = challengeServiceConnector;
        }

        public async Task<IActionResult> Index()
        {
            var summary = await ChallengeServiceConnector.GetSummaryAsync();
            return View(summary);
        }
    }
}

Challenge.Presentation.Web/Controllers/MerchantController.cs
using Challenge.ClientConnector.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace Challenge.Presentation.Web.Controllers
{
    public class MerchantController : Controller
    {
        IChallengeServiceConnector ChallengeServiceConnector { get; }

        public MerchantController(IChallengeServiceConnector challengeServiceConnector)
        {
            ChallengeServiceConnector  = challengeServiceConnector;
        }

        public async Task<IActionResult> Index()
        {
            var merchants = await ChallengeServiceConnector.GetMerchantsAsync();
            return View(merchants);
        }

        public async Task<IActionResult> Details(long id)
        {
            var merchant = await ChallengeServiceConnector.GetMerchantByIdAsync(id);
            return View(merchant);
        }

        public async Task<IActionResult> Summary(long id)
        {
            var merchant = await ChallengeServiceConnector.GetSummaryByMerchantAsync(id);
            return View(merchant);
        }
    }
}

Challenge.Presentation.Web/Views/Home/Index.cshtml
@using Challenge.ApplicationService.Messages.Response;
@using System.Globalization;
@model SummaryResponse;
@{
    ViewData["Title"] = "Indicadores";

    var numberFormat = (NumberFormatInfo)CultureInfo.GetCultureInfo("pt-br").NumberFormat.Clone();
    numberFormat.CurrencyNegativePattern = 1;
}

<div class="text-center">
    <h1 class="display-4">Indicadores</h1>
</div>

<div class="row mt-5">
    <div class="col">
        <div class="card text-bg-primary mb-3" style="max-width: 18rem;">
            <div class="card-header text-center">Lojistas ativos</div>
            <div class="card-body">
                <h2 class="card-title text-center">@Model.MerchantsCount</h2>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card text-bg-primary mb-3" style="max-width: 18rem;">
            <div class="card-header text-center">Vendas Realizadas</div>
            <div class="card-body">
                <h2 class="card-title text-center">@Model.PurchaseCount</h2>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card text-bg-primary mb-3" style="max-width: 18rem;">
            <div class="card-header text-center">Valor financeiro operado</div>
            <div class="card-body">
                <h2 class="card-title text-center">@Model.PurchaseAmmount.ToString("c", numberFormat)</h2>
            </div>
        </div>
    </div>
</div>

Challenge.Presentation.Web/Views/Merchant/Details.cshtml
@using System.Globalization;
@model Challenge.ApplicationService.Messages.Response.MerchantResponse

@{
    ViewData["Title"] = "Detalhes";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var numberFormat = (NumberFormatInfo)CultureInfo.GetCultureInfo("pt-br").NumberFormat.Clone();
    numberFormat.CurrencyNegativePattern = 1;
}

<h1>Detials</h1>

<div>
    <h4>@Model.Name</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Balance)
        </dt>
        <dd class = "col-sm-10">
            @Model.Balance.ToString("c", numberFormat)
        </dd>
    </dl>
    <hr />
    <h4>Vendas</h4>
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Valor</th>
                    <th scope="col">Data da compra</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Purchases)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.Amount.ToString("c", numberFormat)</td>
                        <td>@item.Date.ToString("dd/MM/yyyy HH:mm") </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<div>
    @Html.ActionLink("Indicadores", "Summary", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

Challenge.Presentation.Web/Views/Merchant/Index.cshtml
@using Challenge.ApplicationService.Messages.Response;
@using System.Globalization;
@model IEnumerable<MerchantResponse>

@{
    ViewData["Title"] = "Lojistas";

    var numberFormat = (NumberFormatInfo)CultureInfo.GetCultureInfo("pt-br").NumberFormat.Clone();
    numberFormat.CurrencyNegativePattern = 1;
}

<div class="text-center">
    <h1 class="display-4">Merchants</h1>
</div>
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Quantidade de vendas</th>
                <th scope="col">Saldo</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <td>@item.Purchases.Count()</td>
                    <td>@item.Balance.ToString("c", numberFormat)</td>
                    <td>@Html.ActionLink("Ver Vendas","Details", "Merchant", new { id = item.Id })</td>
                    <td>@Html.ActionLink("Indicadores", "Summary", new { id = item.Id }) </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div>
    <a asp-action="Index" asp-controller="Home">Voltar para indicadores</a>
</div>

Challenge.Presentation.Web/Views/Merchant/Summary.cshtml
@using Challenge.ApplicationService.Messages.Response;
@using System.Globalization;
@model SummaryPerMerchantResponse;
@{
}

@{
    ViewData["Title"] = $"Indicadores - {Model.MerchantName}";

    var numberFormat = (NumberFormatInfo)CultureInfo.GetCultureInfo("pt-br").NumberFormat.Clone();
    numberFormat.CurrencyNegativePattern = 1;
}

<div class="text-center">
    <h1 class="display-4">@($"{Model.MerchantName} - Indicadores")</h1>
</div>
<div class="container">
    <div class="row mt-5 justify-content-center">

        <div class="col-6 ">
            <div class="card text-bg-primary mb-3" style="max-width: 18rem;">
                <div class="card-header text-center">Vendas Realizadas</div>
                <div class="card-body">
                    <h2 class="card-title text-center">@Model.PurchaseCount</h2>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card text-bg-primary mb-3" style="max-width: 18rem;">
                <div class="card-header text-center">Valor financeiro operado</div>
                <div class="card-body">
                    <h2 class="card-title text-center">@Model.Balance.ToString("c", numberFormat)</h2>
                </div>
            </div>
        </div>
    </div>
</div>

Challenge.Presentation.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Challenge </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Challenge.Presentation.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Challenge.Presentation.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Indicadores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Merchant" asp-action="index">Lojistas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Challenge
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>